repos:
  - repo: local
    hooks:
      - id: generate-python-api-docs
        name: Generate Python API docs (pdoc3)
        entry: scripts/generate_api_docs.sh
        language: system
        pass_filenames: false
