"""``pixie start`` — launch the web UI for browsing eval-driven-dev artifacts.

Usage::

    pixie start [root]

Ensures the pixie working directory is initialized, then starts a local
HTTP server that serves a React web UI for browsing scorecards, datasets,
and markdown artifacts generated by the eval-driven-dev skill. The UI
updates live when files change.
"""

from __future__ import annotations

from pixie.cli.init_command import init_pixie_dir
from pixie.config import get_config
from pixie.web.server import run_server


def start(
    root: str | None = None,
    *,
    tab: str | None = None,
    item_id: str | None = None,
) -> int:
    """Initialize the pixie directory (if needed) and launch the web UI server.

    The init step is idempotent — existing directories and files are preserved.

    Args:
        root: Optional explicit artifact root directory.
              Defaults to ``PIXIE_ROOT`` or ``pixie_qa``.
        tab: Optional tab to pre-select (e.g. "scorecards").
        item_id: Optional item path to pre-select within the tab.

    Returns:
        Exit code (0 on normal shutdown).
    """
    config = get_config()
    artifact_root = root or config.root
    init_pixie_dir(root=artifact_root)
    run_server(artifact_root, tab=tab, item_id=item_id)
    return 0
