"""``pixie start`` — launch the web UI for browsing eval-driven-dev artifacts.

Usage::

    pixie start [root]

Ensures the pixie working directory is initialized, then starts the web
server in a detached background process.  The server serves a React web UI
for browsing scorecards, datasets, and markdown artifacts generated by the
eval-driven-dev skill.  The UI updates live when files change.

The command returns immediately after the server has started.  Use
``pixie stop`` to shut it down.
"""

from __future__ import annotations

from pixie import __version__
from pixie.cli.init_command import init_pixie_dir
from pixie.config import get_config
from pixie.telemetry import emit
from pixie.web.server import start_detached


def start(
    root: str | None = None,
    *,
    tab: str | None = None,
    item_id: str | None = None,
) -> int:
    """Initialize the pixie directory (if needed) and launch the web UI server.

    The server is started as a detached background process so this
    function returns immediately.  The init step is idempotent —
    existing directories and files are preserved.

    Args:
        root: Optional explicit artifact root directory.
              Defaults to ``PIXIE_ROOT`` or ``pixie_qa``.
        tab: Optional tab to pre-select (e.g. "scorecards").
        item_id: Optional item path to pre-select within the tab.

    Returns:
        Exit code (0 on success, 1 if the server failed to start).
    """
    emit("pixie_start", {"version": __version__})

    config = get_config()
    artifact_root = root or config.root
    init_pixie_dir(root=artifact_root)
    port = start_detached(artifact_root, tab=tab, item_id=item_id)
    if port is None:
        from pathlib import Path

        log_path = Path(artifact_root).resolve() / "server.log"
        msg = "Failed to start the web server."
        if log_path.exists():
            msg += f" Check {log_path} for details."
        print(msg)  # noqa: T201
        return 1
    print(f"Server running on port {port}")  # noqa: T201
    return 0
